### ISSUE TITLE
请问自定义的图像识别可以实现吗？

### ISSUE THREAD

**Issue by tiger2014** [sherlockchou86/VideoPipe#41]
我如果想识别图片中的某种线条图，但是这种线条图又不是一模一样的，有一些差异，但是人眼一眼就能看出来是一类图形。这个怎么用本库实现？谢谢

**Comment by sherlockchou86** [comment]
你这个跟具体分类算法有关，这个框架是专门用来集成算法。加群有相关算法同行交流
