### ISSUE TITLE
Can run on mac m1? 

### ISSUE THREAD

**Issue by kbscolin** [sherlockchou86/VideoPipe#55]
Can VideoPipe run on mac m1? 

Thanks!

**Comment by taoxm** [comment]
邮件已收到，谢谢！

**Comment by sherlockchou86** [comment]
yeah, it depends on gstreamer and opencv which are portable on mac m1.

**Comment by kbscolin** [comment]
Ok, thanks!  I compile according to the default way.  An error happens: 
VideoPipe/nodes/infers/vp_face_swap_node.cpp:233:29: error: non-constant-expression cannot be narrowed from type 'int' to 'float' in initializer list [-Wc++11-narrowing]
One/project/opensource/industry/ai/sherlockchou86/VideoPipe/nodes/infers/vp_sface_feature_encoder_node.cpp:57:43:             {{kps[0].first, kps[0].second}, 
error:                             ^~~~~~~~~~~~~
non-constant-expression cannot be narrowed from type 'int' to 'float' in initializer list [-Wc++11-narrowing]
                 {i->key_points[2].first, i->key_points[2].second}, 

VideoPipe/nodes/infers/vp_sface_feature_encoder_node.cpp:57:43: note: insert an explicit cast to silence this issue
                 {i->key_points[2].first, i->key_points[2].second}, 
                                          ^~~~~~~~~~~~~~~~~~~~~~~
                                          static_cast<float>(    )

I. use  opencv 4.10.0 and gcc 14.1.0_2,  the os is mac 12.7.5 (M1 Pro). Thanks!

**Comment by sherlockchou86** [comment]
some syntax compatibility issues on mac os, fix it by google.

**Comment by taoxm** [comment]
邮件已收到，谢谢！
