### ISSUE TITLE
运行所有功能的cmake后报错

### ISSUE THREAD

**Issue by guojiahuiEmily** [sherlockchou86/VideoPipe#58]
start build for complex sampels...
-- Configuring done
CMake Error at samples/CMakeLists.txt:209 (add_executable):
  Cannot find source file:

    math_review/math_expression_check_pipeline.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at samples/CMakeLists.txt:197 (add_executable):
  Cannot find source file:

    vehicle_property_and_similiarity_search/vehicle_encoding_classify_pipeline.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at samples/CMakeLists.txt:192 (add_executable):
  Cannot find source file:

    vehicle_behaviour_analysis/vehicle_ba_pipeline.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at samples/CMakeLists.txt:187 (add_executable):
  Cannot find source file:

    similiarity_search/vehicle_encoding_pipeline.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at samples/CMakeLists.txt:202 (add_executable):
  Cannot find source file:

    lpr_camera/plate_recognize_pipeline.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at samples/CMakeLists.txt:179 (add_executable):
  Cannot find source file:

    face_recognize/face_recognize_pipeline.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at samples/CMakeLists.txt:185 (add_executable):
  Cannot find source file:

    similiarity_search/face_encoding_pipeline.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at samples/CMakeLists.txt:209 (add_executable):
  No SOURCES given to target: math_expression_check_pipeline

CMake Error at samples/CMakeLists.txt:197 (add_executable):
  No SOURCES given to target: vehicle_encoding_classify_pipeline

CMake Error at samples/CMakeLists.txt:192 (add_executable):
  No SOURCES given to target: vehicle_ba_pipeline

CMake Error at samples/CMakeLists.txt:187 (add_executable):
  No SOURCES given to target: vehicle_encoding_pipeline

**Comment by sherlockchou86** [comment]
部分sample源码不在仓库中

**Comment by guojiahuiEmily** [comment]
> similiarity_search

可否帮忙把similiarity_search的代码发我  myie9@qq.com
