### ISSUE TITLE
在Ubuntu下运行rtsp_des_sample例子，最后的2个rtsp流输出，没有弹出视频框，这是为啥？

### ISSUE THREAD

**Issue by beelzebub2006** [sherlockchou86/VideoPipe#61]
[ WARN:4@43.445] global cap_gstreamer.cpp:2838 handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module qtdemux1 reported: Internal data stream error.
[ WARN:4@43.449] global cap_gstreamer.cpp:1208 startPipeline OpenCV | GStreamer warning: unable to start pipeline
[ WARN:4@43.724] global cap_gstreamer.cpp:1750 open OpenCV | GStreamer warning: frame count is estimated by duration and fps
[ WARN:4@43.724] global cap_gstreamer.cpp:1173 isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created

**Comment by sherlockchou86** [comment]
可能环境问题，详细入群交流
